apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: framework-tls
  namespace: default
spec:
  secretName: framework-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - rabbitmq.archse.eng.br