apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-tls
  namespace: default
spec:
  secretName: rabbitmq-tls
  issuerRef:
    name: letsencrypt-rabbitmq-prod
    kind: ClusterIssuer
  dnsNames:
    - rabbitmq.archse.eng.br