apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: rabbitmq
type: Opaque
data:
  # Base64 encoded values
  # DB_USER: sa ( for example base64: c2E=)
  DB_USER: __DB_USER__
  DB_PASSWORD: __DB_PASSWORD__
  SA_PASSWORD: __SA_PASSWORD__
  RABBITMQ_DEFAULT_USER: __RABBITMQ_DEFAULT_USER__
  RABBITMQ_DEFAULT_PASS: __RABBITMQ_DEFAULT_PASS__